# Generated by Django 6.0.6 on 2026-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_be_added_to_channel',
            field=models.BooleanField(default=True),
        ),
    ]
