"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-&8-lrh#x@wnf=i8v74es$turtnpdl5+159^azbn+p(2@s703)m',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    # 'backend' is the docker-compose service name the Vite proxy targets.
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,backend').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    # project apps
    'core',
    'accounts',
    'chats',
    'messaging',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.AppSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# SPA sends the session cookie cross-origin, so allow specific origins with
# credentials (a wildcard origin is not allowed alongside credentials).
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_HTTPONLY = False

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(
                os.environ.get('REDIS_HOST', 'redis'),
                int(os.environ.get('REDIS_PORT', '6379')),
            )],
        },
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'app'),
        'USER': os.environ.get('POSTGRES_USER', 'app'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'app'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': int(os.environ.get('POSTGRES_PORT', '5432')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'


# ---------------------------------------------------------------------------
# Object storage (MinIO / S3-compatible)
# ---------------------------------------------------------------------------
# User-uploaded media is stored in an S3-compatible object store (MinIO in
# docker-compose) rather than on the app container's filesystem. Two buckets:
#   * public  ("media")         -> avatars, world-readable, served directly.
#   * private ("private-media") -> chat attachments, streamed through Django
#                                  so access control is enforced per request.
# When USE_S3 is off (the default, e.g. tests / bare-metal dev) Django falls
# back to the local filesystem, so nothing else has to change.
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('MINIO_ACCESS_KEY', 'minioadmin')
    AWS_SECRET_ACCESS_KEY = os.environ.get('MINIO_SECRET_KEY', 'minioadmin')
    # Endpoint the backend uses to talk to the store (server-to-server).
    AWS_S3_ENDPOINT_URL = os.environ.get('S3_ENDPOINT_URL', 'http://minio:9000')
    AWS_S3_REGION_NAME = os.environ.get('S3_REGION_NAME', 'us-east-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    # MinIO only supports path-style addressing (host/bucket/key).
    AWS_S3_ADDRESSING_STYLE = 'path'

    S3_PUBLIC_BUCKET = os.environ.get('S3_PUBLIC_BUCKET', 'media')
    S3_PRIVATE_BUCKET = os.environ.get('S3_PRIVATE_BUCKET', 'private-media')

    # Host the *browser* uses to fetch public objects (avatars). Inside Docker
    # the backend reaches MinIO at minio:9000, but the browser reaches it at
    # localhost:9000 — so public URLs are generated against this host.
    _public_base = os.environ.get('S3_PUBLIC_URL', 'http://localhost:9000')
    _public_scheme, _, _public_host = _public_base.rpartition('://')
    _public_host = (_public_host or _public_base).rstrip('/')
    S3_URL_PROTOCOL = f'{_public_scheme or "http"}:'
    S3_PUBLIC_CUSTOM_DOMAIN = f'{_public_host}/{S3_PUBLIC_BUCKET}'

    STORAGES = {
        # Public bucket — avatars (ImageField). No querystring auth; URLs point
        # straight at the public MinIO host.
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': S3_PUBLIC_BUCKET,
                'querystring_auth': False,
                'file_overwrite': False,
                'custom_domain': S3_PUBLIC_CUSTOM_DOMAIN,
                'url_protocol': S3_URL_PROTOCOL,
            },
        },
        # Private bucket — chat attachments. Never exposed directly; the
        # download view streams objects after checking chat membership.
        'private_media': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': S3_PRIVATE_BUCKET,
                'querystring_auth': True,
                'file_overwrite': False,
                'default_acl': 'private',
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
