# Generated by Django 6.0.6 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv",
            name="direct_key",
            field=models.CharField(
                blank=True,
                help_text="Deterministic key for the two direct-chat participant identifiers.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
