# Generated by Django 6.0.6 on 2026-08-13 13:05

from secrets import token_urlsafe

from django.db import migrations, models


def issue_invite_tokens(apps, schema_editor):
    """Give every pre-existing group an invite token.

    ``link`` was a plain blank-by-default column, so every existing row holds
    the same empty string. That collides the moment the field becomes unique,
    and an empty token would be a dead invite link anyway.
    """
    Group = apps.get_model("chats", "Group")

    taken = set(
        Group.objects.exclude(link__in=("", None)).values_list("link", flat=True)
    )
    for group in Group.objects.filter(link__in=("", None)):
        token = token_urlsafe(16)
        while token in taken:
            token = token_urlsafe(16)
        taken.add(token)
        group.link = token
        group.save(update_fields=["link"])


def enrol_owners_as_members(apps, schema_editor):
    """Add each owner to their own group's membership rows.

    New groups enrol the owner at creation so member counts and member lists
    are simply "the membership rows". Groups created before that rule need the
    same shape, or they would render one member short.
    """
    Group = apps.get_model("chats", "Group")
    GroupMembership = apps.get_model("chats", "GroupMembership")

    existing = set(
        GroupMembership.objects.values_list("group_id", "user_id")
    )
    GroupMembership.objects.bulk_create(
        [
            GroupMembership(group_id=group.pk, user_id=group.owner_id)
            for group in Group.objects.all()
            if (group.pk, group.owner_id) not in existing
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_pv_direct_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # Must precede the AlterField: the unique constraint cannot be added
        # while every row still shares the same blank link.
        migrations.RunPython(issue_invite_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, help_text='Opaque invite token; anyone who opens it joins the group.', max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(enrol_owners_as_members, migrations.RunPython.noop),
    ]
