# Generated by Django 6.0.6 on 2026-08-13 14:17

from django.db import migrations, models

BIO_MAX_LENGTH = 70


def truncate_long_bios(apps, schema_editor):
    """Trim bios that predate the length limit.

    ``bio`` was an unbounded TextField, so narrowing the column outright would
    fail on any longer row. Trimming is the only lossless-enough option: the
    alternative is refusing to migrate.
    """
    Group = apps.get_model("chats", "Group")
    for group in Group.objects.exclude(bio=""):
        if len(group.bio) > BIO_MAX_LENGTH:
            group.bio = group.bio[:BIO_MAX_LENGTH]
            group.save(update_fields=["bio"])


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_group_allow_media_group_avatar_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_long_bios, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='group',
            name='bio',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
