# Generated by Django 6.0.6 on 2026-08-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_channel_is_private_channel_access_level_and_more'),
        ('messaging', '0005_chatreadstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='chats.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_mutes',
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='uq_channel_mute')],
            },
        ),
        migrations.CreateModel(
            name='ChatMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_mutes',
                'constraints': [models.UniqueConstraint(fields=('chat', 'user'), name='uq_chat_mute')],
            },
        ),
    ]
