# Generated by Django 6.0.6 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="link",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="file",
            name="storage_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
