# Generated by Django 6.0.6 on 2026-08-13 14:17

from django.db import migrations, models


def scope_from_for_humans(apps, schema_editor):
    """Carry the old boolean over to the new two-way scope.

    ``for_humans=False`` previously meant "not a people tag", which is exactly
    the group/channel audience the scope now names explicitly.
    """
    Tag = apps.get_model("core", "Tag")
    Tag.objects.filter(for_humans=True).update(scope="user")
    Tag.objects.filter(for_humans=False).update(scope="group")


def for_humans_from_scope(apps, schema_editor):
    Tag = apps.get_model("core", "Tag")
    Tag.objects.filter(scope="user").update(for_humans=True)
    Tag.objects.filter(scope="group").update(for_humans=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_private_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('scope', 'title')},
        ),
        migrations.AddField(
            model_name='tag',
            name='scope',
            field=models.CharField(choices=[('user', 'People'), ('group', 'Groups & channels')], default='user', help_text='Whether this tag is offered for people or for groups/channels.', max_length=10),
        ),
        # Must sit between the add and the remove: the backfill reads the old
        # column and writes the new one, so both have to exist at once.
        migrations.RunPython(scope_from_for_humans, for_humans_from_scope),
        migrations.RemoveField(
            model_name='tag',
            name='for_humans',
        ),
    ]
